var valor1;
var valor2;
valor1=prompt('ingrese primer numero: ','');
valor2=prompt('ingrese segundo numero: ','');
var suma= parseInt (valor1)+parseInt(valor2);
var producto=valor1*valor2;
document.write('La suma es');
document.write(suma);
document.write('<br>');
document.write('El producto es');
document.write(producto);